cp -f node_modules/abp-filter-parser-cpp/ABPFilterParser.cpp ./Application/LinkBubble/src/main/jni/ABPFilterParser.cpp
cp -f node_modules/abp-filter-parser-cpp/ABPFilterParser.h ./Application/LinkBubble/src/main/jni/ABPFilterParser.h
cp -f node_modules/abp-filter-parser-cpp/cosmeticFilter.cpp ./Application/LinkBubble/src/main/jni/cosmeticFilter.cpp
cp -f node_modules/abp-filter-parser-cpp/cosmeticFilter.h ./Application/LinkBubble/src/main/jni/cosmeticFilter.h
cp -f node_modules/abp-filter-parser-cpp/filter.cpp ./Application/LinkBubble/src/main/jni/filter.cpp
cp -f node_modules/abp-filter-parser-cpp/filter.h ./Application/LinkBubble/src/main/jni/filter.h
cp -f node_modules/abp-filter-parser-cpp/base.h ./Application/LinkBubble/src/main/jni/base.h
cp -f node_modules/abp-filter-parser-cpp/badFingerprint.h ./Application/LinkBubble/src/main/jni/badFingerprint.h
cp -f node_modules/abp-filter-parser-cpp/badFingerprints.h ./Application/LinkBubble/src/main/jni/badFingerprints.h
cp -f node_modules/bloom-filter-cpp/BloomFilter.cpp ./Application/LinkBubble/src/main/jni/BloomFilter.cpp
cp -f node_modules/bloom-filter-cpp/BloomFilter.h ./Application/LinkBubble/src/main/jni/BloomFilter.h
cp -f node_modules/bloom-filter-cpp/hashFn.h ./Application/LinkBubble/src/main/jni/hashFn.h
cp -f node_modules/hashset-cpp/HashSet.cpp ./Application/LinkBubble/src/main/jni/HashSet.cpp
cp -f node_modules/hashset-cpp/HashSet.h ./Application/LinkBubble/src/main/jni/HashSet.h
cp -f node_modules/hashset-cpp/HashItem.h ./Application/LinkBubble/src/main/jni/HashItem.h
